name: nbd-cassandra-cluster
services:
  cassandra1:
    image: docker.io/bitnami/cassandra:latest
    hostname: cassandra1
    container_name: cassandra1
    ports:
      - "7001:7000"
      - "9042:9042"
    volumes:
      - cassandra1_data:/bitnami
    networks:
      cassandranet:
        ipv4_address: 172.24.0.2
    environment:
      - CASSANDRA_RPC_ADDRESS=cassandra1
      - CASSANDRA_LISTEN_ADDRESS=cassandra1
      - CASSANDRA_BROADCAST_ADDRESS=cassandra1
      - CASSANDRA_SEEDS=cassandra1,cassandra2
      - CASSANDRA_CLUSTER_NAME=nbd-cassandra-cluster
      - CASSANDRA_DATACENTER=dc1
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_USER=nbd
      - CASSANDRA_PASSWORD=nbd
      - MAX_HEAP_SIZE=1G
      - HEAP_NEWSIZE=100M

  cassandra2:
    image: docker.io/bitnami/cassandra:latest
    hostname: cassandra2
    container_name: cassandra2
    ports:
      - "7002:7000"
      - "9043:9042"
    volumes:
      - cassandra2_data:/bitnami
    networks:
      cassandranet:
        ipv4_address: 172.24.0.3
    environment:
      - CASSANDRA_RPC_ADDRESS=cassandra2
      - CASSANDRA_LISTEN_ADDRESS=cassandra2
      - CASSANDRA_BROADCAST_ADDRESS=cassandra2
      - CASSANDRA_SEEDS=cassandra1,cassandra2
      - CASSANDRA_CLUSTER_NAME=nbd-cassandra-cluster
      - CASSANDRA_DATACENTER=dc1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_USER=nbd
      - CASSANDRA_PASSWORD=nbd
      - MAX_HEAP_SIZE=1G
      - HEAP_NEWSIZE=100M

volumes:
  cassandra1_data:
    driver: local
  cassandra2_data:
    driver: local


networks:
  cassandranet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.24.0.0/16