services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: RentDB
      POSTGRES_USER: root
      POSTGRES_PASSWORD: db
    ports:
      - 5432:5432
    volumes:
      - pg:/var/lib/postgresql/data
volumes:
  pg:
